import Head from "next/head";
import Model from "@/components/elements/model";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ziya Arslan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ position: "relative" }}>
        <div className="page"></div>
        <Model />
      </main>
    </>
  );
}
